### ISSUE TITLE
Fix the broken violation message

### ISSUE THREAD

**Issue by husttroy** [husttroy/Maple-extension#4]
![issue](https://user-images.githubusercontent.com/2655256/32408783-fca4247a-c15b-11e7-8288-475777ba2253.png)

check this link https://stackoverflow.com/questions/21720759/convert-a-json-string-to-a-hashmap/34667127#34667127

**Comment by areinhardt14** [comment]
I think I accidentally fixed this while working on the other issue; I'll close this when I actually push my code (which might be a bit).
