### ISSUE TITLE
like and dislike a reported violation and pattern

### ISSUE THREAD

**Issue by husttroy** [husttroy/Maple-extension#6]
![soap-candidate-29860000](https://user-images.githubusercontent.com/2655256/32410133-b1dda702-c176-11e7-950c-2835cc10ed47.png)

If we have time, I wish we can demonstrate the idea of allowing users to like or dislike a reported violation and pattern.

Currently no like/dislike number is shown in the popup window and the icons of like and dislike are also not straightforward. One suggestion is to replace the current icons with the thump-up and thump-down icons in youtube.

**Comment by husttroy** [comment]
I am envisioning something like this (photoshoped).

![ps](https://user-images.githubusercontent.com/2655256/32410315-92030ba8-c17a-11e7-9ef9-b71c92d053c0.png)

**Comment by areinhardt14** [comment]
So far I have added something that looks like this (hardcoded votes):
![voting_screenshot](https://user-images.githubusercontent.com/14171062/32696155-512e5168-c725-11e7-84d5-5e9713c3fd7d.PNG)

I've discovered that there's a problem concerning the full implementation of this -- for popovers that have combined patterns, I need a way of getting the alternate pattern's ID as well, I think. Trying to get the normal pattern ID by putting the buttons where the old ones were resulted in this:
![voting_screenshot_bad](https://user-images.githubusercontent.com/14171062/32696176-df46f6c6-c725-11e7-8eee-5d08b12ef13c.PNG)

**Comment by husttroy** [comment]
Will the issue in the second screenshot affect the demo video? 

Also, can you make the thumb-up and thumb-down buttons aligned with the pagination as well as the numbers?

@areinhardt14

**Comment by areinhardt14** [comment]
The second won't affect the demo video.

I can make it align with the pagination but I've been having trouble with the numbers lining up. They're cells in a table row with the thumb-up and thumb-down buttons, but because the buttons are bigger the alignment is off. So I can look into cell padding or just making the numbers bigger.

**Comment by areinhardt14** [comment]
![voting_screenshot_align](https://user-images.githubusercontent.com/14171062/32696779-dab5adf4-c735-11e7-902d-45664c76af8e.PNG)

This was about as aligned as I could get them; I edited the margins of the images as well.

**Comment by husttroy** [comment]
Great! This looks good. Let's make the video first.
